; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0CA@KGACINK@failed?5to?5create?5window?5surface@ ; `string'
EXTRN	glfwDestroyWindow:PROC
EXTRN	glfwWindowHint:PROC
EXTRN	glfwCreateWindow:PROC
EXTRN	glfwInit:PROC
EXTRN	glfwTerminate:PROC
EXTRN	glfwCreateWindowSurface:PROC
;	COMDAT ??_C@_0CA@KGACINK@failed?5to?5create?5window?5surface@
CONST	SEGMENT
??_C@_0CA@KGACINK@failed?5to?5create?5window?5surface@ DB 'failed to crea'
	DB	'te window surface', 00H			; `string'
PUBLIC	?createSurface@Window@cow@@QEBAXPEAUVkInstance_T@@PEAPEAUVkSurfaceKHR_T@@@Z ; cow::Window::createSurface
PUBLIC	??1Window@cow@@QEAA@XZ				; cow::Window::~Window
PUBLIC	??0Window@cow@@QEAA@HHPEBD@Z			; cow::Window::Window
;	COMDAT pdata
pdata	SEGMENT
$pdata$?createSurface@Window@cow@@QEBAXPEAUVkInstance_T@@PEAPEAUVkSurfaceKHR_T@@@Z DD imagerel $LN7@createSurf
	DD	imagerel $LN7@createSurf+69
	DD	imagerel $unwind$?createSurface@Window@cow@@QEBAXPEAUVkInstance_T@@PEAPEAUVkSurfaceKHR_T@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1Window@cow@@QEAA@XZ DD imagerel $LN5@Window
	DD	imagerel $LN5@Window+22
	DD	imagerel $unwind$??1Window@cow@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Window@cow@@QEAA@HHPEBD@Z DD imagerel $LN4@Window
	DD	imagerel $LN4@Window+114
	DD	imagerel $unwind$??0Window@cow@@QEAA@HHPEBD@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Window@cow@@QEAA@HHPEBD@Z DQ 00008340a00040a01r ; 1.14081e-308
	DD	07006520aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1Window@cow@@QEAA@XZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?createSurface@Window@cow@@QEBAXPEAUVkInstance_T@@PEAPEAUVkSurfaceKHR_T@@@Z DQ 00000820400010401r ; 7.06285e-310
END
